//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilePhoneLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobilePhoneLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bought {
            get {
                object obj = ResourceManager.GetObject("Bought", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FindIMEIWayOne {
            get {
                object obj = ResourceManager.GetObject("FindIMEIWayOne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FindIMEIWayTwo {
            get {
                object obj = ResourceManager.GetObject("FindIMEIWayTwo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QRCode {
            get {
                object obj = ResourceManager.GetObject("QRCode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sold {
            get {
                object obj = ResourceManager.GetObject("Sold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 INSERT INTO
        ///Brand
        ///(
        ///EnglishName,
        ///ChineseName,
        ///SortID
        ///)
        ///VALUES
        ///(
        ///?,
        ///?,
        ///?
        ///) 的本地化字符串。
        /// </summary>
        internal static string SQL_Insert_Brand {
            get {
                return ResourceManager.GetString("SQL_Insert_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INSERT INTO
        ///Model
        ///(
        ///BrandEnglishName,
        ///ModelName,
        ///SortID
        ///)
        ///VALUES
        ///(
        ///?,
        ///?,
        ///?
        ///) 的本地化字符串。
        /// </summary>
        internal static string SQL_Insert_Model {
            get {
                return ResourceManager.GetString("SQL_Insert_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INSERT INTO
        ///Trade
        ///(
        ///TradeID,
        ///TradeType,
        ///PersonName,
        ///PersonID,
        ///PersonPhoneNumber,
        ///Brand,
        ///Model,
        ///PhoneColor,
        ///Price,
        ///IMEI,
        ///OperName,
        ///OperDate,
        ///SendToServer
        ///)
        ///VALUES
        ///(
        ///?,
        ///?,
        ///?,
        ///?,
        ///?,
        ///?,
        ///?,
        ///?,
        ///?,
        ///?,
        ///?,
        ///?,
        ///?
        ///) 的本地化字符串。
        /// </summary>
        internal static string SQL_Insert_Trade {
            get {
                return ResourceManager.GetString("SQL_Insert_Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT 
        ///EnglishName,
        ///ChineseName,
        ///SortID
        ///FROM
        ///Brand 的本地化字符串。
        /// </summary>
        internal static string SQL_Select_Brand {
            get {
                return ResourceManager.GetString("SQL_Select_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT 
        ///BrandEnglishName,
        ///ModelName,
        ///SortID
        ///FROM
        ///Model
        ///WHERE
        ///BrandEnglishName=? 的本地化字符串。
        /// </summary>
        internal static string SQL_Select_Model_By_BrandEnglishName {
            get {
                return ResourceManager.GetString("SQL_Select_Model_By_BrandEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT
        ///TOP {0}
        ///TradeID,
        ///TradeType,
        ///PersonName,
        ///PersonID,
        ///PersonPhoneNumber,
        ///Brand,
        ///Model,
        ///PhoneColor,
        ///Price,
        ///IMEI,
        ///OperName,
        ///OperDate,
        ///SendToServer
        ///FROM
        ///Trade
        ///WHERE
        ///TradeType=?
        ///ORDER BY
        ///OperDate DESC 的本地化字符串。
        /// </summary>
        internal static string SQL_Select_Trade_By_Top_And_TradeType {
            get {
                return ResourceManager.GetString("SQL_Select_Trade_By_Top_And_TradeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT
        ///TradeID,
        ///TradeType,
        ///PersonName,
        ///PersonID,
        ///PersonPhoneNumber,
        ///Brand,
        ///Model,
        ///PhoneColor,
        ///Price,
        ///IMEI,
        ///OperName,
        ///OperDate,
        ///SendToServer
        ///FROM
        ///Trade
        ///WHERE
        ///SendToServer=FALSE
        ///ORDER BY
        ///OperDate 的本地化字符串。
        /// </summary>
        internal static string SQL_Select_Unsended_Trade {
            get {
                return ResourceManager.GetString("SQL_Select_Unsended_Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UPDATE
        ///Trade
        ///SET
        ///TradeID=?,
        ///TradeType=?,
        ///PersonName=?,
        ///PersonID=?,
        ///PersonPhoneNumber=?,
        ///Brand=?,
        ///Model=?,
        ///PhoneColor=?,
        ///Price=?,
        ///IMEI=?,
        ///OperName=?,
        ///OperDate=?,
        ///SendToServer=?
        ///WHERE
        ///TradeID=? 的本地化字符串。
        /// </summary>
        internal static string SQL_Update_Trade_By_TradeID {
            get {
                return ResourceManager.GetString("SQL_Update_Trade_By_TradeID", resourceCulture);
            }
        }
    }
}
